# -*- coding: utf-8 -*-
"""Copia de 03_Despliegue_Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tcj2BM9_NdDio7vaY6Rzh3JYEhtvM6a3

# Despliegue: Predicción de Pit Stop en Fórmula 1
- Cargamos el modelo
- Cargamos los datos futuros
- Preparamos los datos futuros
- Aplicamos el modelo para la predicción
"""

# Cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from huggingface_hub import hf_hub_download

def cargar_modelo():

    ruta_modelo = hf_hub_download(
        repo_id="CarlosC4/modelo-despliegue-f1",
        filename="modelo-f1.pkl"
    )

    return pickle.load(open(ruta_modelo, 'rb'))

modelo, min_max_scaler, variables, compound_map, necesita_norm, nombre_modelo = cargar_modelo()

# Cargamos datos futuros (opcional - ejemplo con datos reales del dataset)
#data_futuros = pd.read_csv('f1_datos_futuros.csv')
#data_futuros.head()

# =========================
# INTERFAZ STREAMLIT
# =========================

st.title('🏎️ Predicción de Pit Stop en Fórmula 1')

st.markdown(
    'Ingresa los datos de la vuelta actual para predecir '
    'si el piloto hará pit stop en la siguiente vuelta.'
)

# Entradas del usuario
Compound = st.selectbox(
    'Compuesto de Neumático',
    ['SOFT', 'MEDIUM', 'HARD', 'INTERMEDIATE', 'WET']
)

Stint = st.slider(
    'Stint (número de stint)',
    min_value=1,
    max_value=6,
    value=2,
    step=1
)

TyreLife = st.slider(
    'Vida del Neumático (vueltas)',
    min_value=1,
    max_value=60,
    value=15,
    step=1
)

Position = st.slider(
    'Posición en carrera',
    min_value=1,
    max_value=20,
    value=8,
    step=1
)

LapTime = st.slider(
    'Tiempo de vuelta (segundos)',
    min_value=70.0,
    max_value=150.0,
    value=92.0,
    step=0.1
)

LapTime_Delta = st.slider(
    'Delta tiempo de vuelta (s)',
    min_value=-10.0,
    max_value=10.0,
    value=0.3,
    step=0.1
)

Cumul_Deg = st.slider(
    'Degradación acumulada',
    min_value=-80.0,
    max_value=10.0,
    value=-5.0,
    step=0.5
)

RaceProgress = st.slider(
    'Progreso de carrera (0-100%)',
    min_value=0,
    max_value=100,
    value=45,
    step=1
) / 100

Position_Change = st.slider(
    'Cambio de posición',
    min_value=-5,
    max_value=5,
    value=0,
    step=1
)

Normalized_Tyre = round(TyreLife / 58.0, 4)

# DataFrame
datos = [[
    Compound,
    Stint,
    TyreLife,
    Position,
    LapTime,
    LapTime_Delta,
    Cumul_Deg,
    RaceProgress,
    Normalized_Tyre,
    float(Position_Change)
]]

data = pd.DataFrame(datos, columns=[
    'Compound',
    'Stint',
    'TyreLife',
    'Position',
    'LapTime (s)',
    'LapTime_Delta',
    'Cumulative_Degradation',
    'RaceProgress',
    'Normalized_TyreLife',
    'Position_Change'
])

# =========================
# PREDICCIÓN
# =========================

if st.button('Predecir Pit Stop'):

    prediccion = modelo.predict(data)[0]

    if prediccion == 1:
        st.error('🔴 El piloto probablemente hará PIT STOP')
    else:
        st.success('🟢 El piloto probablemente NO hará PIT STOP')

# Preparación de los datos futuros
data_preparada = data_futuros.copy()

# Codificación ordinal del compuesto (igual que en el entrenamiento)
data_preparada['Compound'] = data_preparada['Compound'].map(compound_map)

# Se adicionan las columnas faltantes (reindex con las variables del modelo)
data_preparada = data_preparada.reindex(columns=variables, fill_value=0)

data_preparada.head()

# Normalización si el modelo la requiere (KNN, NN, SVM)
#variables_numericas = [
#    'Stint', 'TyreLife', 'Position', 'LapTime (s)',
#    'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress',
#    'Normalized_TyreLife', 'Position_Change', 'Compound'
#]

#if necesita_norm:
#    # En despliegue NO se llama fit, solo transform
#    data_preparada[variables_numericas] = min_max_scaler.transform(data_preparada[variables_numericas])

#data_preparada.head()

"""# Predicciones"""

# Hacemos la predicción
Y_pred  = modelo.predict(data_preparada)
Y_proba = modelo.predict_proba(data_preparada)[:, 1]

print('Predicción:', Y_pred)
print('Probabilidad de pit stop:', Y_proba)

data_futuros['PitNextLap_Predicho'] = Y_pred
data_futuros['Probabilidad_PitStop'] = Y_proba.round(4)
data_futuros.head()

# Predicciones finales con mensaje en Streamlit
prob_pit = float(Y_proba[0])
pred     = int(Y_pred[0])

if pred == 1:
    st.error(f' **PIT STOP RECOMENDADO** — Probabilidad: {prob_pit:.1%}')
else:
    st.success(f' **CONTINUAR EN PISTA** — Probabilidad de pit stop: {prob_pit:.1%}')

# Recordar medida de error del modelo
st.warning(f'El modelo ({nombre_modelo}) tiene un ROC-AUC aproximado de 0.92 en datos de prueba')
